### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"12345"
}

### Sign in
POST http://localhost:3000/auth/signind
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"12345"
}

### get the currently signed in user
GET http://localhost:3000/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Find user with ID
GET http://localhost:3000/auth/3

### Find all users with email
GET http://localhost:3000/auth?email=asdsf@gmail.com

### Delete a user with id
DELETE  http://localhost:3000/auth/5

### Update user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email":"bbb@bbsb.com"
}

###Set a color

GET http://localhost:3000/auth/colors/red

### Get the color

GET http://localhost:3000/auth/colors